# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: get-submodule-array-from-gitmodules-file

description: Get the Submodule Array from .gitmodules

inputs:
  submodule:
    required: true    # [required]
    description: xxx
  gitmodules-file:
    required: false
    default: '.gitmodules'
    description: xxx
  working-directory:
    required: false
    default: ${{ github.workspace }}
    description: >
      The directory from which to run commands or locate files. Defaults to '\$\{\{ github.workspace \}\}'.

outputs:
  SUBMODULE_NUM:
    value: ${{ steps.glll.outputs.SUBMODULE_NUM }}
    description: xxx
  SUBMODULE_ARRAY:
    value: ${{ steps.glll.outputs.SUBMODULE_ARRAY }}
    description: xxx

runs:
  using: composite
  steps:
    - name: Get the Submodule List from .gitmodules
      id: glll
      shell: bash
      run: |
        SUBMODULE="${{ inputs.submodule }}"
        GITMODULES_FILE="${{ inputs.gitmodules-file }}"
        WORKING_DIRECTORY=$(echo "${{ inputs.working-directory }}" | sed 's#\\#/#g' | sed 's#^\([A-Za-z]\):#/\L\1#')

        cd "${WORKING_DIRECTORY}"

        if [[ "${SUBMODULE}" == "all" ]]; then
          SUBMODULE_LINES=$(git config --file ${GITMODULES_FILE} --get-regexp path | awk '{print $2}')
          SUBMODULE_ARRAY=$(echo "${SUBMODULE_LINES}" | jq -R -s -c "split(\"\n\") | map(select(length > 0))")
        else
          SUBMODULE_LINES=($(git config --file ${GITMODULES_FILE} --get-regexp path | awk '{print $2}'))
          FOUND_SUBMODULE=false
          for SUBMODULE_LINE in ${SUBMODULE_LINES[@]}; do
            if [[ "${SUBMODULE_LINE}" == "${SUBMODULE}" ]]; then
              FOUND_SUBMODULE=true
              SUBMODULE_ARRAY="[ \"${LANGUAGE}\" ]"
              break
            fi
          done
          if [[ "${FOUND_SUBMODULE}" == "true" ]]; then
            echo "Submodule '${LANGUAGE}' is found in the list."
          else
            echo "Error: Submodule '${LANGUAGE}' is NOT found in the list." >&2
            exit 1
          fi
        fi
        SUBMODULE_NUM=$(jq "length" <<< "${SUBMODULE_ARRAY}")

        echo "SUBMODULE_NUM=${SUBMODULE_NUM}" >> ${GITHUB_OUTPUT}
        echo "SUBMODULE_NUM:"
        echo "${SUBMODULE_NUM}"

        echo "SUBMODULE_ARRAY=${SUBMODULE_ARRAY}" >> ${GITHUB_OUTPUT}
        echo "SUBMODULE_ARRAY:"
        echo "${SUBMODULE_ARRAY}" | jq "."
