# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: get-pull-request-label-list-from-versions-file

description: >
  Get the label list for the pull request from `versions.json` file.

inputs:
  version:
    required: true    # [required]
    description: >
      The version to search for in the specified `versions.json` file.
  tms-label:
    required: true    # [required]
    description: >
      The label added to the pull request lable list if the version is required to upload to the TMS.
  versions-file:
    required: false
    default: 'versions.json'
    description: >
      The path to the JSON file containing version data. Defaults to `versions.json`.
  working-directory:
    default: '${{ github.workspace }}'
    required: false
    description: >
      The directory from which to run commands or locate files. Defaults to `'\$\{\{ github.workspace \}\}'`.

outputs:
  PULL_REQUEST_LABEL_LIST:
    value: ${{ steps.gllpr.outputs.PULL_REQUEST_LABEL_LIST }}
    description: >
      A comma-separated list of pull request labels.

runs:
  using: composite
  steps:
    - name: Get the Label List for the Pull Request from versions.json
      id: gllpr
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        TMS_LABEL="${{ inputs.tms-label }}"
        VERSIONS_FILE="${{ inputs.versions-file }}"
        WORKING_DIRECTORY="${{ inputs.working-directory }}"

        JQ_FILTER="[.[] | map(select(.VERSION_COMPENDIUM == \"\"))] | add | .[].VERSION"
        JQ_FILE="${VERSIONS_FILE}"
        VERSION_LINES=($(jq -r "${JQ_FILTER}" "${JQ_FILE}" | tr -d '\r'))
        PULL_REQUEST_LABEL_LIST="gettext"
        for VERSION_LINE in "${VERSION_LINES[@]}"; do
          if [[ "${VERSION}" == "${VERSION_LINE}" ]]; then
            PULL_REQUEST_LABEL_LIST="${PULL_REQUEST_LABEL_LIST},${TMS_LABEL}"
            break
          fi
        done

        echo "PULL_REQUEST_LABEL_LIST=${PULL_REQUEST_LABEL_LIST}" >> ${GITHUB_OUTPUT}
        echo "PULL_REQUEST_LABEL_LIST:"
        echo "${PULL_REQUEST_LABEL_LIST}"
