# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: get-version-from-pull-request-title

description: Get the Version from the Pull Request Title.

inputs:
  pr-title:
    required: true    # [required]
    description: xxx

outputs:
  VERSION:
    value: ${{ steps.gvprt.outputs.VERSION }}
    description: xxx

runs:
  using: composite
  steps:
    - name: Get VERSION from the Pull Request Title
      id: gvprt
      shell: bash
      run: |
        PR_TITLE="${{ inputs.pr-title }}"
        VERSION_REGEX="pot\(([^)]+)\):"
        # See https://stackoverflow.com/a/218217/16265240 for details.
        if [[ ${PR_TITLE} =~ ${VERSION_REGEX} ]]; then
          VERSION="${BASH_REMATCH[1]}"
          echo "Found version: ${VERSION}"
        else
          echo "Error: No version found in PR title." >&2
          exit 1
        fi
        echo "VERSION=${VERSION}" >> ${GITHUB_OUTPUT}
        echo "VERSION:"
        echo "${VERSION}"
