# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: crowdin-branch-delete

description: Delete the branch in Crowdin

inputs:
  crowdin-config-file:
    required: false
    default: ''
    description: >
      The path to the Crowdin configuration file. Defaults to an empty string.
  crowdin-branch-name:
    required: true  # [required]
    description: >
      The name of the branch to delete in Crowdin.
  crowdin-project-id:
    required: false
    default: ''
    description: >
      The numeric ID of the project in Crowdin. Defaults to an empty string.
  crowdin-personal-token:
    required: false
    default: ''
    description: >
      The personal access token for Crowdin authentication. Defaults to an empty string.
  crowdin-no-progress:
    required: false
    default: 'false'
    description: >
      Whether to disable progress on executed command. Defaults to 'false'.
  crowdin-verbose:
    required: false
    default: 'false'
    description: >
      Whether to provide more information about the command execution. Defaults to 'false'.
  working-directory:
    required: false
    default: '${{ github.workspace }}'
    description: >
      The directory from which to run commands or locate files. Defaults to '\$\{\{ github.workspace \}\}'.

runs:
  using: composite
  steps:
    - name: Get the Crowdin Arguments by Inputs
      id: crowdin-args
      shell: bash
      run: |
        INPUTS_JSON=$(echo '${{ toJSON(inputs) }}' | jq -c)
        INPUTS_KEYS=$(echo "${INPUTS_JSON}" | jq -r 'keys[]' | tr -d '\r')
        CROWDIN_ARGS=()
        for KEY in ${INPUTS_KEYS}; do
          VALUE=$(echo "${INPUTS_JSON}" | jq -r --arg key "${KEY}" '.[$key]')
          CROWDIN_ARG=""
          if [[ "${KEY}" == "crowdin-config-file" ]]; then
            if [[ "${VALUE}" != "" ]]; then
              CROWDIN_CONFIG_FILE=$(echo "${{ inputs.crowdin-config-file }}" | sed 's#\\#/#g' | sed 's#^\([A-Za-z]\):#/\L\1#')
              CROWDIN_ARG="--config=${CROWDIN_CONFIG_FILE}"
            fi
          elif [[ "${KEY}" == "crowdin-project-id" ]]; then
            if [[ "${VALUE}" != "" ]]; then
              CROWDIN_PROJECT_ID="${{ inputs.crowdin-project-id }}"
              CROWDIN_ARG="--project-id=${CROWDIN_PROJECT_ID}"
            fi
          elif [[ "${KEY}" == "crowdin-personal-token" ]]; then
            if [[ "${VALUE}" != "" ]]; then
              CROWDIN_PERSONAL_TOKEN="${{ inputs.crowdin-personal-token }}"
              CROWDIN_ARG="--token=${CROWDIN_PERSONAL_TOKEN}"
            fi
          elif [[ "${KEY}" == "crowdin-no-progress" ]]; then
            if [[ "${VALUE}" == "true" ]]; then
              CROWDIN_ARG="--no-progress"
            fi
          elif [[ "${KEY}" == "crowdin-verbose" ]]; then
            if [[ "${VALUE}" == "true" ]]; then
              CROWDIN_ARG="--verbose"
            fi
          fi
          CROWDIN_ARGS+=(${CROWDIN_ARG})
        done
        echo "CROWDIN_ARGS=${CROWDIN_ARGS[@]}" >> ${GITHUB_OUTPUT}
        echo "CROWDIN_ARGS:"
        echo "${CROWDIN_ARGS[@]}"

    - name: Delete the branch in Crowdin
      shell: bash
      run: |
        WORKING_DIRECTORY=$(echo "${{ inputs.working-directory }}" | sed 's#\\#/#g' | sed 's#^\([A-Za-z]\):#/\L\1#')
        CROWDIN_ARGS="${{ steps.crowdin-args.outputs.CROWDIN_ARGS }}"
        cd "${WORKING_DIRECTORY}"
        echo "Deleting the branch in Crowdin..."
        echo ""
        echo "crowdin branch delete ${{ inputs.crowdin-branch-name }} ${CROWDIN_ARGS[@]}"
        echo ""
        crowdin branch delete ${{ inputs.crowdin-branch-name }} ${CROWDIN_ARGS[@]}
