# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: install-cmake

description: Install CMake

inputs:
  cmake-version:
    required: false
    default: ''
    description: 'Specific version of CMake to install.'
  token:
    required: false
    default: '${{ github.token }}'
    description: xxx

runs:
  using: composite
  steps:
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v2.0
      with:
        cmake-version: ${{ inputs.cmake-version }}
