# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-sphinx-build-docs

on:
  workflow_call:
    inputs:
      RUNNER:
        type: string
        required: true  # [required]
        description: >
          The runner image for executing the job (e.g., 'ubuntu-latest').
      CHECKOUT:
        type: string
        required: true  # [required]
        description: >
          The git reference to be checked out (e.g., '\$\{\{ github.ref \}\}').
      VERSION:
        type: string
        required: true  # [required]
        description: >
          The version of the documentation.
      LANGUAGE:
        type: string
        required: true  # [required]
        description: >
          The language of the documentation.
      MODE_OF_UPDATE:
        type: string
        required: true  # [required]
        description: >
          The mode of updating .pot and .po files.
      BASEURL_HREF:
        type: string
        required: true  # [required]
        description: >
          The base URL for the deployed HTML documentation.
      SPHINX_BUILDER:
        type: string
        required: true  # [required]
        description: >
          The Sphinx builder used for building documentation.
      DEPLOY_PAGES:
        type: string
        required: true  # [required]
        description: >
          Whether to deploy the build artifacts to pages (e.g., 'true' or 'false').
      ENABLE_JOB:
        type: string
        required: true  # [required]
        description: >
          Whether to enable the job (e.g., 'true' or 'false').
      ACTOR_NAME:
        type: string
        required: true  # [required]
        description: >
          The user name of the GitHub actor.
      ACTOR_EMAIL:
        type: string
        required: true  # [required]
        description: >
          The user email of the GitHub actor.
    secrets:
      ACTOR_GITHUB_TOKEN:
        required: true  # [required]
        description: >
          The personal access token of the GitHub actor.

jobs:
  sphinx-build-docs:
    if: ${{ inputs.ENABLE_JOB == 'true' }}
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Print Contexts/Inputs/Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.workflow = ${{ github.workflow }}"
          echo "github.workflow_ref = ${{ github.workflow_ref }}"
          echo "github.run_id = ${{ github.run_id }}"
          echo "github.run_number = ${{ github.run_number }}"
          echo "github.run_attempt = ${{ github.run_attempt }}"
          echo "github.server_url = ${{ github.server_url }}"
          echo "github.repository = ${{ github.repository }}"
          echo "github.workspace = ${{ github.workspace }}"
          echo "[Inputs]"
          echo "inputs.RUNNER = ${{ inputs.RUNNER }}"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.VERSION = ${{ inputs.VERSION }}"
          echo "inputs.LANGUAGE = ${{ inputs.LANGUAGE }}"
          echo "inputs.MODE_OF_UPDATE = ${{ inputs.MODE_OF_UPDATE }}"
          echo "inputs.BASEURL_HREF = ${{ inputs.BASEURL_HREF }}"
          echo "inputs.SPHINX_BUILDER = ${{ inputs.SPHINX_BUILDER }}"
          echo "inputs.DEPLOY_PAGES = ${{ inputs.DEPLOY_PAGES }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "inputs.ACTOR_NAME = ${{ inputs.ACTOR_NAME }}"
          echo "inputs.ACTOR_EMAIL = ${{ inputs.ACTOR_EMAIL }}"
          echo "[Secrets]"
          echo "secrets.ACTOR_GITHUB_TOKEN = ${{ secrets.ACTOR_GITHUB_TOKEN }}"

      - name: Checkout to '${{ inputs.CHECKOUT }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT }}
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
          submodules: true

      - name: Install CMake
        uses: ltdorgtest/ci-common/.github/actions/install-cmake@main

      - name: Install Conda
        uses: ltdorgtest/ci-common/.github/actions/install-conda@main

      - name: Install Gettext
        uses: ltdorgtest/ci-common/.github/actions/install-gettext@main

      - name: Get Other Caches from versions.json
        id: gocv
        uses: ltdorgtest/ci-common/.github/actions/get-other-caches-from-versions-file@main
        with:
          version: ${{ inputs.VERSION }}
          versions-file: 'versions.json'

      - name: Configure the '${{ inputs.LANGUAGE }}' preset for '${{ inputs.VERSION }}' version
        uses: ltdorgtest/ci-common/.github/actions/cmake-configure-preset@main
        with:
          config-preset: ${{ inputs.LANGUAGE }}
          cache-version: ${{ inputs.VERSION }}
          cache-version-compendium: ${{ steps.gocv.outputs.VERSION_COMPENDIUM }}
          cache-auto-depend: 'OFF'
          cache-mode-of-update: ${{ inputs.MODE_OF_UPDATE }}
          cache-baseurl-href: ${{ inputs.BASEURL_HREF }}
          cache-sphinx-builder: ${{ inputs.SPHINX_BUILDER }}

      - name: Build the 'prepare_repositories' target
        uses: ltdorgtest/ci-common/.github/actions/cmake-build-target@main
        with:
          build-directory: out/build/${{ inputs.LANGUAGE }}
          build-target: 'prepare_repositories'

      - name: Build the 'install_requirements' target
        uses: ltdorgtest/ci-common/.github/actions/cmake-build-target@main
        with:
          build-directory: out/build/${{ inputs.LANGUAGE }}
          build-target: 'install_requirements'

      - name: Build the 'sphinx_update_pot' target
        uses: ltdorgtest/ci-common/.github/actions/cmake-build-target@main
        with:
          build-directory: out/build/${{ inputs.LANGUAGE }}
          build-target: 'sphinx_update_pot'

      - name: Build the 'gettext_update_po' target
        uses: ltdorgtest/ci-common/.github/actions/cmake-build-target@main
        with:
          build-directory: out/build/${{ inputs.LANGUAGE }}
          build-target: 'gettext_update_po'

      - name: Build the 'sphinx_build_docs' target
        uses: ltdorgtest/ci-common/.github/actions/cmake-build-target@main
        with:
          build-directory: out/build/${{ inputs.LANGUAGE }}
          build-target: 'sphinx_build_docs'

      - name: Upload Build Artifact for Deploying Pages
        if: ${{ inputs.DEPLOY_PAGES == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ inputs.VERSION }}-${{ inputs.LANGUAGE }}
          path: './out/${{ inputs.SPHINX_BUILDER }}'
