# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-update-license-year

on:
  workflow_call:
    inputs:
      RUNNER:
        type: string
        required: true  # [required]
        description: >
          The runner image for executing the job (e.g., 'ubuntu-latest').
      CHECKOUT:
        type: string
        required: true  # [required]
        description: >
          The git reference to be checked out (e.g., '\$\{\{ github.ref \}\}').
      CALLER_JOB:
        type: string
        required: true  # [required]
        description: >
          The name of the caller job.
      ENABLE_JOB:
        type: string
        required: true  # [required]
        description: >
          Whether to enable the job (e.g., 'true' and 'false').
      ACTOR_NAME:
        type: string
        required: true  # [required]
        description: >
          The user name of the GitHub actor.
      ACTOR_EMAIL:
        type: string
        required: true  # [required]
        description: >
          The user email of the GitHub actor.
    secrets:
      ACTOR_GITHUB_TOKEN:
        required: true  # [required]
        description: >
          The personal access token of the GitHub actor.

jobs:
  update-license-year:
    if: ${{ inputs.ENABLE_JOB == 'true' }}
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Print Contexts/Inputs/Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.run_id = ${{ github.run_id }}"
          echo "[Inputs]"
          echo "inputs.RUNNER = ${{ inputs.RUNNER }}"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.CALLER_JOB = ${{ inputs.CALLER_JOB }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "inputs.ACTOR_NAME = ${{ inputs.ACTOR_NAME }}"
          echo "inputs.ACTOR_EMAIL = ${{ inputs.ACTOR_EMAIL }}"
          echo "[Secrets]"
          echo "secrets.ACTOR_GITHUB_TOKEN = ${{ secrets.ACTOR_GITHUB_TOKEN }}"

      - name: Checkout to '${{ inputs.CHECKOUT }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT }}
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
          submodules: false
          fetch-depth: 0

      - name: Get the Current Job's ID
        id: gcji
        uses: Tiryoh/gha-jobid-action@v1
        with:
          github_token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
          job_name: '${{ inputs.CALLER_JOB }} / ${{ github.job }}'
          per_page: 100

      - name: Check Outputs of the Current Job's ID
        shell: bash
        run: |
          echo "Current Job's URL = ${{ steps.gcji.outputs.html_url }}"
          echo "Current Job's ID  = ${{ steps.gcji.outputs.job_id }}"

      - name: Update the Copyright Year of the LICENSE file
        id: ucyl
        uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
          branchName: license-{{currentYear}}
          commitAuthorName: ${{ inputs.ACTOR_NAME }}
          commitAuthorEmail: ${{ inputs.ACTOR_EMAIL }}
          commitTitle: |
            docs(license): update copyright year(s)
          commitBody: |
            Update the Copyright Year(s) to {{currentYear}}.
          prTitle: |
            docs(license): update copyright year(s)
          prBody: |
            Created by the GitHub Workflow:

            - File: [${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ github.workflow }}.yml)
            - Run: [${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - Job: [${{ inputs.CALLER_JOB }} / ${{ github.job }}](${{ steps.gcji.outputs.html_url }})

      - name: Check Outputs of the Pull Request
        if: ${{ steps.ucyl.outputs.pullRequestNumber }}
        shell: bash
        run: |
          echo "Current Year          = ${{ steps.ucyl.outputs.currentYear }}"
          echo "Pull Request's Branch = ${{ steps.ucyl.outputs.branchName }}"
          echo "Pull Request's Number = ${{ steps.ucyl.outputs.pullRequestNumber }}"
          echo "Pull Request's Url    = ${{ steps.ucyl.outputs.pullRequestUrl }}"
